Repository Kitware/CDash, pull requests merged in 2024-05, with the labels that each got.

#2148 Move test name column to `build2test` table
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/BuildPropertiesController.php
  app/Http/Controllers/TestController.php
  app/Jobs/ProcessSubmission.php
  app/Models/BuildTest.php
  app/Models/Project.php
  app/Models/Test.php
  app/Models/TestOutput.php
  app/Providers/AuthServiceProvider.php
  app/Utils/TestCreator.php
  app/cdash/app/Controller/Api/BuildTestApi.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/TestDetails.php
  app/cdash/app/Controller/Api/TestOverview.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/Build.php
  app/cdash/include/Messaging/Topic/MissingTestTopic.php
  app/cdash/include/Messaging/Topic/TestFailureTopic.php
  app/cdash/include/common.php
  app/cdash/include/dailyupdates.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/tests/case/CDash/Messaging/Topic/MissingTestTopicTest.php
  app/cdash/tests/case/CDash/Messaging/Topic/TestFailureTopicTest.php
  app/cdash/tests/test_bazeljson.php
  app/cdash/tests/test_csvexport.php
  app/cdash/tests/test_issuecreation.php
  app/cdash/tests/test_managemeasurements.php
  app/cdash/tests/test_outputcolor.php
  app/cdash/tests/test_querytests.php
  app/cdash/tests/test_removebuilds.php
  app/cdash/tests/test_testgraphpermissions.php
  app/cdash/tests/test_testhistory.php
  app/cdash/tests/test_truncateoutput.php
  database/migrations/2024_04_17_183212_remove_test_table.php
  phpstan-baseline.neon
  resources/js/components/TestDetails.vue
  resources/views/email/issue/failing_tests.blade.php
  resources/views/email/issue/missing_tests.blade.php
  tests/Feature/TestSchemaMigration.php
  tests/Spec/test-details.spec.js
  tests/cypress/e2e/tests.cy.js
Labels: release notes: maintenance

#2211 Catch DivisionByZeroError on index.php
  app/cdash/public/api/v1/index.php
Labels: release notes: fixes

#2212 Add GraphQL query filtering capability
  app/GraphQL/Directives/FilterDirective.php
  app/Models/Project.php
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/BuildTypeTest.php
  tests/Feature/GraphQL/FilterTest.php
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
Labels: release notes: features

#2218 Merge 3.4.2 into master
  .github/workflows/release.yml
Labels: release notes: ignored

#2222 Schedule periodic tasks with Laravel
  app/Console/Kernel.php
  app/Jobs/PruneAuthTokens.php
  app/Jobs/PruneJobs.php
  app/Models/AuthToken.php
  app/Models/SuccessfulJob.php
  app/Utils/AuthTokenUtil.php
  app/cdash/include/dailyupdates.php
  app/cdash/tests/CMakeLists.txt
  docker/docker-entrypoint.sh
  phpstan-baseline.neon
  tests/Feature/Jobs/PruneAuthTokensTest.php
  tests/Feature/Jobs/PruneJobsTest.php
Labels: release notes: administration
