Repository Kitware/CDash, pull requests merged in 2024-11, with the labels that each got.

#2542 Bump version to 3.6.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2521 Add subproject2subproject foreign-key constraints
  database/migrations/2024_10_29_154630_subproject2subproject_foreign_keys.php
Labels: release notes: maintenance

#2524 Overhaul Mix build
  .eslintignore
  app/Http/Controllers/AbstractController.php
  app/cdash/include/common.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/public/manageCoverage.xsl
  app/cdash/public/viewMap.xsl
  package-lock.json
  package.json
  phpstan-baseline.neon
  public/css/cdash.css
  public/css/colorblind.css
  public/css/common.css
  public/js/controllers/filters.js
  public/js/controllers/index.js
  public/js/controllers/viewBuildError.js
  public/js/directives/build.js
  public/js/directives/buildgroup.js
  public/js/directives/daterange.js
  public/js/directives/timeline.js
  public/views/compareCoverage.html
  public/views/index.html
  public/views/queryTests.html
  public/views/testOverview.html
  public/views/viewSubProjects.html
  resources/views/cdash.blade.php
  resources/views/test/view-test.blade.php
  webpack.mix.js
Labels: release notes: maintenance

#2546 Merge 3.6.0 into master
  app/Http/Controllers/ManageProjectRolesController.php
  phpstan-baseline.neon
Labels: release notes: ignored

#2547 Enable SBOM generation for Docker images
  .github/workflows/build-latest-images.yml
  .github/workflows/release.yml
Labels: release notes: administration

#2548 Clean up Vue build warnings
  resources/js/components/BuildConfigure.vue
  resources/js/components/BuildNotes.vue
  resources/js/components/BuildSummary.vue
  resources/js/components/EditProject.vue
  resources/js/components/UserHomepage.vue
  resources/js/components/ViewDynamicAnalysis.vue
  resources/sass/_variables.scss
  resources/sass/app.scss
Labels: release notes: maintenance

#2552 Speed up long-running migrations
  database/migrations/2024_04_17_183212_remove_test_table.php
  database/migrations/2024_07_09_025240_find_test_measurements_by_testid.php
Labels: release notes: performance

#2555 Fix divide-by-zero error in label2test migration
  database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
Labels: release notes: fixes

#2556 Bump version to 3.6.1
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2559 Merge 3.6.1 into master
  config/cdash.php
  database/migrations/2024_04_17_183212_remove_test_table.php
  database/migrations/2024_07_09_025240_find_test_measurements_by_testid.php
  database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2551 Bump PHPStan rules to level 9
  phpstan-baseline.neon
  phpstan.neon
Labels: release notes: maintenance

#2561 Remove unnecessary web scraper directives
  resources/views/cdash.blade.php
Labels: release notes: user experience

#2557 Clean up misc. submission handler inconsistencies
  app/Jobs/ProcessSubmission.php
  app/cdash/app/Model/Project.php
  app/cdash/app/Model/Subscriber.php
  app/cdash/include/Messaging/Subscription/Subscription.php
  app/cdash/include/Messaging/Topic/Topic.php
  app/cdash/include/sendemail.php
  app/cdash/tests/case/CDash/ConfigUseCaseTest.php
  app/cdash/tests/case/CDash/Messaging/Subscription/CommitAuthorSubscriptionBuilderTest.php
  app/cdash/tests/case/CDash/Messaging/Subscription/UserSubscriptionBuilderTest.php
  app/cdash/tests/case/CDash/XmlHandler/BuildHandlerTest.php
  app/cdash/tests/case/CDash/XmlHandler/ConfigureHandlerTest.php
  app/cdash/tests/case/CDash/XmlHandler/DynamicAnalysisHandlerTest.php
  app/cdash/tests/case/CDash/XmlHandler/TestingHandlerTest.php
  app/cdash/tests/case/CDash/XmlHandler/UpdateHandlerTest.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  app/cdash/xml_handlers/actionable_build_interface.php
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/configure_handler.php
  app/cdash/xml_handlers/coverage_handler.php
  app/cdash/xml_handlers/coverage_junit_handler.php
  app/cdash/xml_handlers/coverage_log_handler.php
  app/cdash/xml_handlers/dynamic_analysis_handler.php
  app/cdash/xml_handlers/note_handler.php
  app/cdash/xml_handlers/project_handler.php
  app/cdash/xml_handlers/testing_handler.php
  app/cdash/xml_handlers/testing_j_unit_handler.php
  app/cdash/xml_handlers/update_handler.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2558 Remove legacy logs directory
  app/cdash/log/README
Labels: release notes: maintenance

#2564 Update Laravel to v10.48.23
  composer.json
  composer.lock
Labels: release notes: external dependencies

#2563 Update Laravel to v10.48.23
  composer.json
  composer.lock
Labels: release notes: external dependencies

#2565 Bump version to 3.5.2
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2566 Bump version to 3.6.2
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2568 Merge 3.6.2 into master
  composer.json
  composer.lock
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2570 Remove unused test directory
  app/cdash/tests/circle/conv.xsl
  app/cdash/tests/circle/default
Labels: release notes: maintenance

#2574 Add foreign-key constraint to configureerror table
  app/cdash/include/common.php
  database/migrations/2024_11_18_113619_configure_error_foreign_key.php
Labels: release notes: maintenance

#2576 Eliminate unnecessary DELETE statements in removeBuilds()
  app/Utils/DatabaseCleanupUtils.php
Labels: release notes: performance

#2577 Use more foreign keys for cascading deletions
  app/Utils/DatabaseCleanupUtils.php
  app/cdash/tests/CMakeLists.txt
  database/migrations/2024_11_20_144306_buildfailure2argument_foreign_key.php
  database/migrations/2024_11_20_144307_updatefile_foreign_key.php
  database/migrations/2024_11_20_144308_test2image_foreign_key.php
  tests/Feature/TestSchemaMigration.php
Labels: release notes: performance

#2569 Fix `testDetails.php` redirect
  routes/web.php
Labels: release notes: fixes

#2573 Delete unused uploads directory
  public/upload/.gitignore
Labels: release notes: maintenance

#2582 Ensure configureerror FK types match
  database/migrations/2024_11_18_113619_configure_error_foreign_key.php
Labels: release notes: fixes

#2583 Overhaul project sites page
  app/Http/Controllers/MapController.php
  app/Http/Controllers/ProjectController.php
  app/Models/Site.php
  app/cdash/public/viewMap.xsl
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_viewmap.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/app.js
  resources/js/vue/components/ProjectSitesPage.vue
  resources/js/vue/components/page-header/HeaderMenu.vue
  resources/views/components/header.blade.php
  resources/views/project/sites.blade.php
  routes/web.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/Spec/page-header/header-menu.spec.js
Labels: release notes: user experience

#2584 Remove last traces of google analytics tracker
  .env.example
  app/Http/Controllers/CoverageController.php
  app/Models/Project.php
  app/cdash/app/Controller/Api/ViewProjects.php
  app/cdash/app/Model/Project.php
  app/cdash/include/common.php
  config/cdash.php
  database/migrations/2024_11_22_160106_drop_googletracker_column.php
  phpstan-baseline.neon
  resources/js/vue/components/EditProject.vue
Labels: release notes: deprecated / removed

#2586 Improve handling of sites with no information
  resources/js/vue/components/ProjectSitesPage.vue
Labels: release notes: fixes

#2585 Add top-level site field to GraphQL API
  graphql/schema.graphql
  tests/Feature/GraphQL/SiteTypeTest.php
Labels: release notes: features

#2580 Move "Cleanup Database" functionality to new artisan command
  app/Console/Commands/CleanDatabase.php
  app/Http/Controllers/AdminController.php
  app/Utils/DatabaseCleanupUtils.php
  app/cdash/public/upgrade.xsl
  app/cdash/tests/test_removebuilds.php
  app/cdash/tests/test_upgrade.php
  phpstan-baseline.neon
Labels: release notes: administration

#2587 Fix project sites page pagination
  resources/js/vue/app.js
Labels: release notes: fixes
