Repository Kitware/CDash, pull requests merged in 2024-08, with the labels that each got.

#2381 LDAP: Default to anonymous binding
  config/ldap.php
Labels: release notes: administration

#2382 Delete submission files from remote workers
  app/Jobs/ProcessSubmission.php
  app/cdash/tests/test_donehandler.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2384 Use filter-based approach for LDAP project membership
  app/Ldap/Rules/FilterRules.php
  app/Utils/LdapUtils.php
  config/ldap.php
  docs/authentication.md
  phpstan-baseline.neon
  resources/js/components/EditProject.vue
  tests/Feature/LdapIntegration.php
Labels: release notes: fixes

#2385 Bump version to 3.5.0-rc4
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2386 Merge 3.5.0-rc4 into master
  app/Jobs/ProcessSubmission.php
  app/Ldap/Rules/FilterRules.php
  app/Utils/LdapUtils.php
  app/cdash/include/api_common.php
  app/cdash/tests/test_donehandler.php
  config/cdash.php
  config/ldap.php
  docs/authentication.md
  package-lock.json
  package.json
  phpstan-baseline.neon
  resources/js/components/EditProject.vue
  resources/views/cdash.blade.php
  tests/Feature/LdapIntegration.php
  tests/Feature/ProjectPermissions.php
Labels: release notes: ignored

#2391 Remove MySQL query info from test output
  app/cdash/tests/kwtest/kw_db.php
Labels: release notes: maintenance

#2390 Reference test table directly in label2test table
  app/Http/Controllers/AdminController.php
  app/Models/Label.php
  app/Models/Test.php
  app/Models/TestLabel.php
  app/Utils/TestCreator.php
  app/cdash/app/Controller/Api/Index.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/Build.php
  app/cdash/app/Model/Label.php
  app/cdash/app/Model/Project.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/tests/test_multiplesubprojects.php
  app/cdash/tests/test_querytests.php
  database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
  phpstan-baseline.neon
  tests/Feature/TestSchemaMigration.php
Labels: release notes: maintenance

#2396 Refactor legacy UserProject model
  app/Http/Controllers/CoverageController.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/Http/Controllers/ProjectController.php
  app/Utils/AuthTokenUtil.php
  app/cdash/app/Model/Project.php
  app/cdash/app/Model/UserProject.php
  app/cdash/include/common.php
  app/cdash/public/api/v1/manageBuildGroup.php
  app/cdash/tests/test_issuecreation.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2397 Add FreeIPA LDAP integration
  app/Ldap/Rules/FilterRules.php
  app/Utils/LdapUtils.php
  config/auth.php
  docs/authentication.md
Labels: release notes: features
