Repository Kitware/CDash, pull requests merged in 2024-04, with the labels that each got.

#2138 Add `merge_group` CI trigger
  .github/workflows/ci.yml
Labels: release notes: maintenance

#2118 Overhaul CDash integration with CI
  .github/workflows/ci.yml
  .github/workflows/commands.bash
  .github/workflows/ctest_driver_script.cmake
  .github/workflows/submit.sh
  CMakeLists.txt
  Dockerfile
  app/cdash/tests/ctest/coveragedriver.ctest.in
  app/cdash/tests/ctest/ctestdriver.ctest.in
  app/cdash/tests/ctest/sameImage/CMakeLists.txt
  app/cdash/tests/ctest/sameImage/test.cmake.in
  app/cdash/tests/ctest/simple/CMakeLists.txt
  app/cdash/tests/ctest/simple/test.cmake.in
  app/cdash/tests/ctest/simple2/CMakeLists.txt
  app/cdash/tests/ctest/simple2/simple.ctest.in
  app/cdash/tests/ctest/simple2/test.cmake.in
Labels: release notes: maintenance

#2115 Add new `MAX_PROJECT_VISIBILITY` config option
  .env.example
  app/Http/Controllers/ProjectController.php
  app/Rules/ProjectVisibilityAllowed.php
  app/cdash/public/api/v1/project.php
  config/cdash.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/components/EditProject.vue
  tests/Feature/GraphQL/ProjectTest.php
Labels: release notes: features

#2107 Remove top-level User GraphQL field
  graphql/schema.graphql
Labels: release notes: ignored

#2113 Bump default PHP to 8.2
  Dockerfile
  app/cdash/app/Model/BuildConfigure.php
  app/cdash/app/Model/BuildErrorFilter.php
  app/cdash/tests/test_buildgetdate.php
  app/cdash/xml_handlers/done_handler.php
  app/cdash/xml_handlers/testing_handler.php
  phpstan-baseline.neon
Labels: release notes: external dependencies

#2119 Add new `REQUIRE_AUTHENTICATED_SUBMISSIONS` config option
  .env.example
  app/Http/Controllers/ProjectController.php
  app/Rules/ProjectAuthenticateSubmissions.php
  app/cdash/public/api/v1/project.php
  config/cdash.php
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/ProjectTest.php
Labels: release notes: features

#2089 Bump master version to 3.4
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2098 Add additional fields to GraphQL Build type
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/BuildTypeTest.php
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
Labels: release notes: features

#2038 Add PingIdentity provider
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/services.php
  docs/authentication.md
  phpstan-baseline.neon
  public/img/pingidentity_signin.png
  resources/providers/PingIdentity/PingIdentityExtendSocialite.php
  resources/providers/PingIdentity/Provider.php
  resources/providers/PingIdentity/composer.json
  resources/providers/PingIdentity/packages.json
  tests/Feature/LoginAndRegistration.php
Labels: release notes: features
