Repository Kitware/CDash, pull requests merged in 2024-12, with the labels that each got.

#2588 Perform batch deletion of invalid records before applying new foreign keys
  database/migrations/2024_11_18_113619_configure_error_foreign_key.php
  database/migrations/2024_11_20_144306_buildfailure2argument_foreign_key.php
  database/migrations/2024_11_20_144307_updatefile_foreign_key.php
  database/migrations/2024_11_20_144308_test2image_foreign_key.php
  phpstan-baseline.neon
Labels: release notes: performance

#2578 Add submission trait to test environment
  app/cdash/tests/kwtest/kw_web_tester.php
  database/seeds/DatabaseSeeder.php
  phpstan-baseline.neon
  tests/Traits/CreatesSubmissions.php
Labels: release notes: maintenance

#2614 Rename `user` table to `users`
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/Http/Controllers/ManageUsersController.php
  app/Http/Controllers/SiteController.php
  app/Models/Project.php
  app/Models/User.php
  app/Utils/AuthTokenUtil.php
  app/Utils/RepositoryUtils.php
  app/cdash/app/Model/BuildEmail.php
  app/cdash/app/Model/Project.php
  app/cdash/app/Model/User.php
  app/cdash/include/common.php
  app/cdash/include/dailyupdates.php
  app/cdash/include/sendemail.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/kwtest/kw_web_tester.php
  app/cdash/tests/test_authtoken.php
  app/cdash/tests/test_createprojectpermissions.php
  database/migrations/2023_08_14_200318_user_foreign_keys.php
  database/migrations/2023_12_19_211314_user_unique_email.php
  database/migrations/2024_12_04_141145_rename_user_to_users.php
  phpstan-baseline.neon
  tests/Feature/LoginAndRegistration.php
  tests/Feature/PasswordRotation.php
  tests/Feature/RouteAccessTest.php
  tests/Feature/UniqueEmailsMigration.php
Labels: release notes: maintenance

#2613 Use Laravel relationships to remove configure and note rows
  app/Utils/DatabaseCleanupUtils.php
  phpstan-baseline.neon
Labels: release notes: performance

#2619 Call cdashmail() from Notification/Email/Mail.php
  app/cdash/app/Model/BuildEmail.php
  app/cdash/include/Messaging/Notification/Email/Mail.php
  app/cdash/tests/kwtest/kw_web_tester.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2589 Add Laravel Dusk for e2e browser testing
  Dockerfile
  app/cdash/tests/CMakeLists.txt
  composer.json
  composer.lock
  docker/docker-compose.dev.yml
  phpstan-baseline.neon
  resources/js/vue/components/ProjectSitesPage.vue
  resources/js/vue/components/shared/DataTable.vue
  tests/Browser/Pages/ProjectSitesPageTest.php
  tests/BrowserTestCase.php
  tests/Traits/CreatesSites.php
Labels: release notes: maintenance

#2621 Demote "No note text for..." log message to debug level
  app/cdash/xml_handlers/note_handler.php
Labels: release notes: administration

#2620 Refactor notification/email inheritance structure
  app/cdash/app/Model/BuildEmail.php
  app/cdash/include/Messaging/FactoryInterface.php
  app/cdash/include/Messaging/Notification/Email/EmailBuilder.php
  app/cdash/include/Messaging/Notification/Email/EmailMessage.php
  app/cdash/include/Messaging/Notification/Email/EmailNotificationFactory.php
  app/cdash/include/Messaging/Notification/Email/Mail.php
  app/cdash/include/Messaging/Notification/Mailer.php
  app/cdash/include/Messaging/Notification/NotificationBuilderInterface.php
  app/cdash/include/Messaging/Notification/NotificationCollection.php
  app/cdash/include/Messaging/Notification/NotificationDirector.php
  app/cdash/include/Messaging/Notification/NotificationInterface.php
  app/cdash/include/Messaging/Subscription/SubscriptionNotificationBuilder.php
  app/cdash/include/Messaging/Subscription/SubscriptionNotificationBuilderInterface.php
  app/cdash/include/sendemail.php
  app/cdash/tests/case/CDash/MultipleSubprojectsEmailTest.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2622 Add mock email server to development environment
  .env.dev
  docker/docker-compose.dev.yml
Labels: release notes: maintenance

#2624 Replace custom SQL in removeBuilds with Eloquent relationships
  app/Models/BuildUpdate.php
  app/Models/CoverageFile.php
  app/Models/RichBuildAlert.php
  app/Models/RichBuildAlertDetails.php
  app/Utils/DatabaseCleanupUtils.php
  phpstan-baseline.neon
Labels: release notes: performance
