Repository Kitware/CDash, pull requests merged in 2024-10, with the labels that each got.

#2467 Remove outdated install instructions
  docs/install.md
Labels: release notes: documentation

#2491 Fix "Manage project coverage" from /user
  app/Http/Controllers/CoverageController.php
Labels: release notes: fixes

#2465 Add details and time columns to new tests page
  app/GraphQL/Scalars/NonNegativeSeconds.php
  graphql/schema.graphql
  resources/js/components/BuildTestsPage.vue
  resources/js/components/shared/DataTable.vue
  resources/js/components/shared/FilterRow.vue
  tests/Feature/GraphQL/TestTypeTest.php
  tests/cypress/component/data-table.cy.js
Labels: release notes: features

#2496 Migrate label2test rows in batches
  database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
Labels: release notes: fixes

#2495 Honor buildid (if specified) for unparsed submission workflow
  app/Jobs/ProcessSubmission.php
  app/cdash/include/ctestparser.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_branchcoverage.php
  app/cdash/tests/test_unparsedsubmissionshonorbuildid.php
  phpstan-baseline.neon
  tests/cypress/e2e/sub-project-group-order.cy.js
Labels: release notes: fixes

#2494 Change build2test id column type to bigint
  database/migrations/2024_07_01_130230_build2test_id_column.php
  database/migrations/2024_07_09_025240_find_test_measurements_by_testid.php
  database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
Labels: release notes: fixes

#2497 Make filter names more user friendly
  resources/js/components/shared/FilterRow.vue
Labels: release notes: user experience

#2499 Move buildinformation table content to build table
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BuildController.php
  app/Models/Build.php
  app/Models/BuildInformation.php
  app/cdash/app/Controller/Api/BuildApi.php
  app/cdash/app/Controller/Api/Index.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/Build.php
  app/cdash/public/api/v1/index.php
  app/cdash/tests/case/CDash/TestUseCaseTest.php
  app/cdash/tests/test_removebuilds.php
  app/cdash/tests/test_submission_assign_buildid.php
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/configure_handler.php
  app/cdash/xml_handlers/coverage_handler.php
  app/cdash/xml_handlers/coverage_junit_handler.php
  app/cdash/xml_handlers/dynamic_analysis_handler.php
  app/cdash/xml_handlers/note_handler.php
  app/cdash/xml_handlers/testing_handler.php
  app/cdash/xml_handlers/testing_j_unit_handler.php
  app/cdash/xml_handlers/upload_handler.php
  database/migrations/2024_10_13_160937_buildinformation_to_build_table.php
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/BuildTypeTest.php
Labels: release notes: maintenance

#2503 Fix project role field in standard API response
  app/Http/Controllers/CoverageController.php
  app/cdash/include/common.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2504 Fix blank lat/long GraphQL Site fields
  graphql/schema.graphql
  tests/Feature/GraphQL/SiteTypeTest.php
Labels: release notes: fixes

#2505 Email all site maintainers
  app/Http/Controllers/ManageProjectRolesController.php
  phpstan-baseline.neon
Labels: release notes: user experience

#2508 Force URL to start with HTTPS if APP_URL starts with https://
  app/Providers/AppServiceProvider.php
Labels: release notes: fixes

#2506 Change migration batching approach to avoid problematic syntax on MySQL
  database/migrations/2024_08_24_160326_label2test_relationship_refactor.php
  database/migrations/2024_10_13_160937_buildinformation_to_build_table.php
Labels: release notes: fixes

#2511 Bump version to 3.6.0-rc1
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2513 Merge 3.6.0-rc1 into master
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2515 Add Coverage type to GraphQL API
  app/Models/Build.php
  app/Models/Coverage.php
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  tests/Feature/GraphQL/CoverageTypeTest.php
Labels: release notes: features

#2519 Improve maintenance page UI
  resources/views/maintenance.blade.php
Labels: release notes: user experience

#2512 Lint ignored Vue files
  .eslintignore
  resources/js/components/AllProjects.vue
  resources/js/components/BuildConfigure.vue
  resources/js/components/BuildNotes.vue
  resources/js/components/BuildSummary.vue
  resources/js/components/BuildUpdate.vue
  resources/js/components/EditProject.vue
  resources/js/components/ManageAuthTokens.vue
  resources/js/components/ManageMeasurements.vue
  resources/js/components/TestDetails.vue
  resources/js/components/UserHomepage.vue
  resources/js/components/ViewDynamicAnalysis.vue
  resources/js/components/page-header/HeaderMenu.vue
  resources/js/components/page-header/HeaderNav.vue
  resources/views/project/view-all-projects.blade.php
Labels: release notes: maintenance

#2517 Add GraphQL "contains" filter
  app/GraphQL/Directives/FilterDirective.php
  phpstan-baseline.neon
  tests/Feature/GraphQL/FilterTest.php
Labels: release notes: features

#2523 Bump version to 3.6.0-rc2
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2518 Expose Labels via GraphQL API
  app/Models/Build.php
  app/Models/Label.php
  app/Models/Test.php
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/BuildTypeTest.php
  tests/Feature/GraphQL/TestTypeTest.php
Labels: release notes: features
