Repository Kitware/CDash, pull requests merged in 2024-09, with the labels that each got.

#2430 Bump version to 3.5.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2432 Bump version to 3.5.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2433 Merge 3.5.0 into master
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2398 Rename BuildNotes to Comments
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/UserNoteController.php
  app/Models/Build.php
  app/Models/Comment.php
  app/cdash/app/Controller/Api/Index.php
  app/cdash/app/Model/BuildUserNote.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_buildusernote.php
  app/cdash/tests/test_usernotes.php
  config/database.php
  database/migrations/2024_08_28_211443_build_comment_refactor.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2394 Set up basic build group Eloquent relationships
  app/Models/Build.php
  app/Models/BuildGroup.php
  app/Models/BuildGroupPosition.php
  app/cdash/tests/case/CDash/MultipleSubprojectsEmailTest.php
  app/cdash/tests/test_buildmodel.php
  database/migrations/2024_08_27_173953_build2group_foreign_key_constraints.php
  database/migrations/2024_08_27_191729_buildgroupposition_relationships.php
Labels: release notes: maintenance

#2399 Use Eloquent Project model for test project creation
  tests/Feature/GraphQL/BuildTypeTest.php
  tests/Feature/GraphQL/FilterTest.php
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/Feature/GraphQL/TestTypeTest.php
  tests/Feature/LdapIntegration.php
  tests/Feature/ProjectPermissions.php
  tests/Feature/RouteAccessTest.php
  tests/Traits/CreatesProjects.php
Labels: release notes: maintenance

#2402 Move contents of ctestparserutils.php to SubmissionUtils
  app/Utils/SubmissionUtils.php
  app/Utils/UnparsedSubmissionProcessor.php
  app/cdash/app/Model/Build.php
  app/cdash/include/common.php
  app/cdash/include/ctestparserutils.php
  app/cdash/tests/test_buildgrouprule.php
  app/cdash/tests/test_buildrelationship.php
  app/cdash/xml_handlers/BazelJSON_handler.php
  app/cdash/xml_handlers/GcovTar_handler.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/configure_handler.php
  app/cdash/xml_handlers/coverage_handler.php
  app/cdash/xml_handlers/coverage_junit_handler.php
  app/cdash/xml_handlers/coverage_log_handler.php
  app/cdash/xml_handlers/dynamic_analysis_handler.php
  app/cdash/xml_handlers/note_handler.php
  app/cdash/xml_handlers/testing_handler.php
  app/cdash/xml_handlers/testing_j_unit_handler.php
  app/cdash/xml_handlers/update_handler.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2403 Remove defines.php and move contents to AppServiceProvider
  app/Providers/AppServiceProvider.php
  app/cdash/include/defines.php
  app/cdash/include/log.php
Labels: release notes: maintenance

#2425 Increase default Cypress timeout
  cypress.config.js
Labels: release notes: maintenance

#2401 Refactor legacy Project model
  app/Console/Commands/PurgeUnusedProjects.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/UserController.php
  app/cdash/app/Model/Project.php
  app/cdash/public/api/v1/project.php
  app/cdash/tests/test_limitedbuilds.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2406 Add TestMeasurement type to GraphQL API
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  tests/Feature/GraphQL/TestMeasurementTypeTest.php
Labels: release notes: features

#2442 Use batch updates for test table migration
  database/migrations/2024_04_17_183212_remove_test_table.php
Labels: release notes: fixes

#2444 Bump version to 3.5.1
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2443 Move angular_view function to AbstractController
  app/Http/Controllers/AbstractController.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/CoverageController.php
  app/Http/Controllers/DynamicAnalysisController.php
  app/Http/Controllers/IndexController.php
  app/Http/Controllers/ProjectOverviewController.php
  app/Http/Controllers/SubProjectController.php
  app/Http/Controllers/TestController.php
  app/Providers/AppServiceProvider.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2445 Fix viewTest.php labels column display
  app/cdash/app/Controller/Api/ViewTest.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2447 Add index to builderror(buildid,type,crc32)
  database/migrations/2024_09_18_131622_builderror_indexing.php
Labels: release notes: performance

#2453 Add `buildfailuredetails` to the "Clean database" step
  app/Http/Controllers/AdminController.php
Labels: release notes: maintenance

#2451 Add Note type to GraphQL schema
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  tests/Feature/GraphQL/NoteTypeTest.php
Labels: release notes: features

#2454 Improve `/projects` load performance
  graphql/schema.graphql
  resources/js/components/AllProjects.vue
  tests/Feature/GraphQL/ProjectTypeTest.php
Labels: release notes: maintenance

#2458 Allow production sites to operate over HTTP
  app/Providers/AppServiceProvider.php
Labels: release notes: administration

#2455 Add foreign-key constraints to dynamic analysis tables
  database/migrations/2024_09_23_133018_dynamic_analysis_foreign_keys.php
Labels: release notes: performance

#2460 Add build measurement backend and API
  app/Enums/BuildMeasurementType.php
  app/Models/Build.php
  app/Models/BuildMeasurement.php
  app/Providers/GraphQLServiceProvider.php
  app/cdash/tests/CMakeLists.txt
  config/app.php
  database/migrations/2024_09_24_184156_build_measurements_table.php
  graphql/schema.graphql
  tests/Feature/GraphQL/BuildMeasurementTypeTest.php
Labels: release notes: features

#2466 Install OPcache PHP extension in Docker by default
  Dockerfile
Labels: release notes: performance
