Repository Kitware/CDash, pull requests merged in 2024-07, with the labels that each got.

#2326 Update release process docs
  docs/release_process.md
Labels: release notes: documentation

#2300 Suppress spammy DaisyUI build log messages
  tailwind.config.js
Labels: release notes: maintenance

#2282 Add support for LDAP-based project access
  app/Console/Commands/UpdateLdapProjectMembership.php
  app/Console/Kernel.php
  app/Http/Controllers/ProjectController.php
  app/Listeners/SuccessfulLdapAuthListener.php
  app/Models/Project.php
  app/Models/User.php
  app/Providers/EventServiceProvider.php
  app/Utils/LdapUtils.php
  app/cdash/app/Model/Project.php
  database/migrations/2024_06_14_125557_ldap_project_membership.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/components/EditProject.vue
  tests/Feature/LdapIntegration.php
Labels: release notes: features

#2331 Bump version to 3.5.0-rc1
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2332 Merge 3.5.0-rc1 into master
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2340 Bump version to 3.5.0-rc2
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2342 Merge 3.5.0-rc2 into master
  .github/workflows/submit.sh
  Dockerfile
  config/cdash.php
  docker/healthcheck.sh
  install.sh
  package-lock.json
  package.json
Labels: release notes: ignored

#2341 RepositoryUtils: fix GitLab URL generation
  app/Utils/RepositoryUtils.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2330 GraphQL: Add project field to build type
  app/Models/Build.php
  graphql/schema.graphql
  tests/Feature/GraphQL/FilterTest.php
Labels: release notes: features

#2343 Generate passwords with Laravel helper
  app/Console/Commands/CheckKey.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/Http/Controllers/UserController.php
  app/Utils/AuthTokenUtil.php
  app/cdash/include/common.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2344 Clean up misc. single-use "common" functions
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/BuildNoteController.php
  app/Http/Controllers/CoverageController.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/Http/Controllers/ProjectOverviewController.php
  app/Http/Controllers/TestController.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/TestDetails.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/include/common.php
  app/cdash/include/sendemail.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2348 Change how Composer is installed for UBI-based image
  Dockerfile
Labels: release notes: fixes

#2347 Remove references to 'layouts.app' view
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/verify.blade.php
Labels: release notes: fixes

#2349 Bump version to 3.5.0-rc3
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2350 Merge 3.5.0-rc3 into master
  Dockerfile
  app/Utils/RepositoryUtils.php
  app/cdash/include/common.php
  app/cdash/tests/test_extracttar.php
  app/cdash/xml_handlers/GcovTar_handler.php
  config/cdash.php
  package-lock.json
  package.json
  phpstan-baseline.neon
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/verify.blade.php
Labels: release notes: ignored

#2346 Add basic Test type to GraphQL API
  app/Http/Controllers/TestController.php
  app/Models/Build.php
  app/Models/Test.php
  app/Models/TestOutput.php
  app/Providers/AuthServiceProvider.php
  app/Utils/TestCreator.php
  app/cdash/app/Controller/Api/BuildTestApi.php
  app/cdash/app/Controller/Api/TestGraph.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/Build.php
  app/cdash/include/Messaging/Topic/MissingTestTopic.php
  app/cdash/include/Messaging/Topic/TestFailureTopic.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/case/CDash/Messaging/Topic/TestFailureTopicTest.php
  app/cdash/tests/test_multiplelabelsfortests.php
  graphql/schema.graphql
  phpstan-baseline.neon
  routes/web.php
  tests/Feature/GraphQL/TestTypeTest.php
Labels: release notes: features

#2352 Fix incorrect relationship between Build and Project models
  app/Models/Build.php
Labels: release notes: fixes
