Repository Kitware/CDash, pull requests merged in 2025-04, with the labels that each got.

#2776 Handle processor Model Name in Site information
  app/Models/SiteInformation.php
  app/cdash/tests/case/CDash/TestUseCaseTest.php
  database/migrations/2025_03_31_124158_support_model_name_on_site.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/components/SitesIdPage.vue
  resources/js/vue/components/shared/BuildSummaryCard.vue
  tests/Browser/Pages/SitesIdPageTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
Labels: release notes: features

#2700 Add Helm chart for CDash
  Dockerfile
  helm/cdash/.gitignore
  helm/cdash/.helmignore
  helm/cdash/Chart.lock
  helm/cdash/Chart.yaml
  helm/cdash/templates/NOTES.txt
  helm/cdash/templates/_helpers.tpl
  helm/cdash/templates/cdash/configmap.yaml
  helm/cdash/templates/cdash/deployment.yaml
  helm/cdash/templates/cdash/ingress.yaml
  helm/cdash/templates/cdash/secret.yaml
  helm/cdash/templates/cdash/service.yaml
  helm/cdash/templates/worker/deployment.yaml
  helm/cdash/values.yaml
  tests/CMakeLists.txt
Labels: release notes: features

#2781 Fix configure hide/show when subprojects present
  resources/js/vue/components/BuildConfigure.vue
Labels: release notes: fixes

#2786 Merge releases/3.10 into master
  resources/js/vue/components/BuildConfigure.vue
Labels: release notes: ignored

#2782 Fix flaky email test
  app/cdash/tests/test_email.php
Labels: release notes: maintenance

#2784 Remove broken `autoremovebuilds` test
  app/cdash/tests/test_autoremovebuilds.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2788 Fix flaky `manage-build-group` test
  tests/cypress/e2e/manage-build-group.cy.js
Labels: release notes: maintenance

#2791 Move simple legacy tests out of the critical path
  app/cdash/tests/CMakeLists.txt
Labels: release notes: maintenance

#2792 Use text emails for auth token notifications
  app/Mail/AuthTokenExpired.php
  app/Mail/AuthTokenExpiring.php
Labels: release notes: fixes

#2793 Reinstate `viewTest.php` filters
  resources/views/test/view-test.blade.php
Labels: release notes: fixes

#2794 Increase size of configure.log from text to mediumtext
  database/migrations/2025_04_09_150429_configure_log_medium_text.php
Labels: release notes: fixes

#2795 Remove integration with non-git repos
  app/Utils/RepositoryUtils.php
  phpstan-baseline.neon
Labels: release notes: deprecated / removed

#2798 Remove unused "bug tracker file url" UI
  resources/js/vue/components/EditProject.vue
Labels: release notes: deprecated / removed

#2799 Delete web-based dependency audit/upgrade
  app/Console/Commands/AuditDependencies.php
  app/Console/Commands/UpdateDependencies.php
  app/Console/Kernel.php
  app/Http/Controllers/AdminController.php
  app/cdash/public/upgrade.xsl
  phpstan-baseline.neon
Labels: release notes: deprecated / removed

#2800 Fix flaky `SitesIdPageTest`
  tests/Browser/Pages/SitesIdPageTest.php
Labels: release notes: maintenance

#2790 Restructure Cypress e2e tests
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/autoremovebuilds/CMakeLists.txt
  tests/CMakeLists.txt
  tests/cypress/component/CMakeLists.txt
  tests/cypress/e2e/CMakeLists.txt
Labels: release notes: maintenance

#2802 Remove `ACTIVE_PROJECT_DAYS` env variable
  .env.example
  config/cdash.php
  docs/config.md
Labels: release notes: deprecated / removed

#2803 Change `QUEUE_CONNECTION` default to `database`
  config/queue.php
Labels: release notes: administration

#2796 Remove obsolete `userStatistics.php` page
  .eslintignore
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/UserStatisticsController.php
  app/cdash/app/Model/Build.php
  app/cdash/public/upgrade.xsl
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_updateonlyuserstats.php
  app/cdash/tests/test_upgrade.php
  app/cdash/tests/test_userstatistics.php
  database/migrations/2025_04_10_011000_delete_userstatistics_table.php
  phpstan-baseline.neon
  resources/js/angular/controllers/userStatistics.js
  resources/js/angular/views/userStatistics.html
  resources/js/vue/components/UserHomepage.vue
  resources/views/components/header.blade.php
  routes/api.php
  routes/web.php
Labels: release notes: deprecated / removed

#2807 Use auto-generated container names
  .github/workflows/submit.sh
  docker/docker-compose.dev.yml
  docker/docker-compose.minio.yml
  docker/docker-compose.mysql.yml
  docker/docker-compose.postgres.yml
  docker/docker-compose.production.yml
  docker/docker-compose.yml
  tests/BrowserTestCase.php
Labels: release notes: administration

#2806 Stop publishing separate cdash-worker image
  .github/workflows/build-latest-images.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
  docker/docker-compose.production.yml
Labels: release notes: deprecated / removed

#2809 Add storage type to CDash build name
  .github/workflows/ctest_driver_script.cmake
Labels: release notes: maintenance

#2810 Reduce CI parallelism from 4 to 3 processes
  .github/workflows/submit.sh
Labels: release notes: maintenance

#2808 Remove unnecessary dependencies between mocked unit tests
  app/cdash/tests/CMakeLists.txt
  phpstan-baseline.neon
  tests/Feature/SlowPageTest.php
Labels: release notes: maintenance

#2812 Lock APP_URL in browser and cypress tests
  app/cdash/tests/CMakeLists.txt
  tests/Browser/Pages/ProjectSitesPageTest.php
  tests/BrowserTestCase.php
  tests/Feature/Mail/AuthTokenExpiredTest.php
  tests/Feature/Mail/AuthTokenExpiringTest.php
  tests/cypress/component/CMakeLists.txt
  tests/cypress/e2e/CMakeLists.txt
Labels: release notes: maintenance

#2811 Bump version to 3.10
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2814 Merge 3.10 into master
  config/cdash.php
  database/migrations/2025_04_09_150429_configure_log_medium_text.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2778 Overhaul project members page
  app/Enums/ProjectRole.php
  app/GraphQL/Mutations/ChangeProjectRole.php
  app/GraphQL/Mutations/InviteToProject.php
  app/GraphQL/Mutations/RevokeInvitation.php
  app/Http/Controllers/InvitationController.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/Http/Controllers/ProjectMembersController.php
  app/Mail/InvitedToProject.php
  app/Models/Project.php
  app/Models/User.php
  app/Models/UserInvitation.php
  app/Policies/ProjectPolicy.php
  app/Providers/GraphQLServiceProvider.php
  app/cdash/public/manageProjectRoles.xsl
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_manageprojectroles.php
  config/auth.php
  config/cdash.php
  database/migrations/2025_02_24_132230_create_user_invitations_table.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/app.js
  resources/js/vue/components/ProjectMembersPage.vue
  resources/js/vue/components/UserHomepage.vue
  resources/js/vue/components/shared/DataTable.vue
  resources/views/components/header.blade.php
  resources/views/email/invited-to-project.blade.php
  resources/views/project/members.blade.php
  routes/web.php
  tests/Browser/Pages/ProjectMembersPageTest.php
  tests/Feature/GraphQL/Mutations/ChangeProjectRoleTest.php
  tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
  tests/Feature/GraphQL/Mutations/RevokeInvitationTest.php
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/UserInvitationTypeTest.php
  tests/Feature/ProjectInvitationAcceptanceTest.php
  tests/Feature/RouteAccessTest.php
Labels: release notes: features

#2816 Remove `upgrade.php`
  app/Http/Controllers/AdminController.php
  app/cdash/public/upgrade.xsl
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_upgrade.php
  phpstan-baseline.neon
  resources/js/vue/components/UserHomepage.vue
  routes/web.php
  tests/Feature/RouteAccessTest.php
Labels: release notes: deprecated / removed

#2783 Remove support for automatic mailing list user creation
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_issuecreation.php
  app/cdash/tests/test_subproject.php
  app/cdash/tests/test_subprojectemail.php
  app/cdash/xml_handlers/project_handler.php
  phpstan-baseline.neon
  tests/cypress/e2e/tests.cy.js
Labels: release notes: deprecated / removed

#2821 Bump version to 3.10.1
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2822 Merge 3.10.1 into master
  app/Jobs/PruneUploads.php
  app/Models/Project.php
  config/cdash.php
  package-lock.json
  package.json
  tests/Feature/Jobs/PruneUploadsTest.php
Labels: release notes: ignored

#2823 Fix docker compose postgres volume path
  docker/docker-compose.postgres.yml
Labels: release notes: fixes

#2612 Add build instrumentation API
  app/Enums/BuildCommandType.php
  app/Enums/BuildMeasurementType.php
  app/Enums/TargetType.php
  app/GraphQL/Scalars/NonNegativeIntegerMilliseconds.php
  app/Models/Build.php
  app/Models/BuildCommand.php
  app/Models/BuildMeasurement.php
  app/Models/Target.php
  app/Providers/GraphQLServiceProvider.php
  app/Validators/Schemas/Build.xsd
  app/cdash/tests/CMakeLists.txt
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/configure_handler.php
  database/migrations/2024_11_04_202649_build_measurements.php
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/BuildCommandTypeTest.php
  tests/Feature/GraphQL/BuildMeasurementTypeTest.php
  tests/Feature/GraphQL/BuildTypeTest.php
  tests/Feature/GraphQL/LabelTypeTest.php
  tests/Feature/GraphQL/TargetTypeTest.php
  tests/Feature/Submission/Instrumentation/BuildInstrumentationTest.php
  tests/Feature/Submission/Instrumentation/data/Build.xml
  tests/Feature/Submission/Instrumentation/data/result.json
Labels: release notes: features

#2818 Restrict user email access
  app/Policies/UserPolicy.php
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  tests/Feature/GraphQL/QueryTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/Feature/GraphQL/UserTypeTest.php
Labels: release notes: maintenance

#2824 Remove legacy User model passthrough
  app/Models/User.php
  app/cdash/app/Model/User.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2820 Add `user-profile` Cypress test to `install_2` dependency list
  app/cdash/tests/CMakeLists.txt
Labels: release notes: maintenance

#2825 Fix flaky test-related Cypress tests
  tests/cypress/e2e/CMakeLists.txt
Labels: release notes: maintenance

#2826 Remove helm files
  Dockerfile
  helm/cdash/.gitignore
  helm/cdash/.helmignore
  helm/cdash/Chart.lock
  helm/cdash/Chart.yaml
  helm/cdash/templates/NOTES.txt
  helm/cdash/templates/_helpers.tpl
  helm/cdash/templates/cdash/configmap.yaml
  helm/cdash/templates/cdash/deployment.yaml
  helm/cdash/templates/cdash/ingress.yaml
  helm/cdash/templates/cdash/secret.yaml
  helm/cdash/templates/cdash/service.yaml
  helm/cdash/templates/worker/deployment.yaml
  helm/cdash/values.yaml
  tests/CMakeLists.txt
Labels: release notes: administration

#2829 docker: stop listening on port 443
  Dockerfile
Labels: release notes: fixes

#2832 Change `latest` Docker tag to refer to latest release
  .github/workflows/build-latest-images.yml
  .github/workflows/release.yml
Labels: release notes: administration

#2833 Increase robustness of `TestOutput::DecompressOutput()`
  app/Models/TestOutput.php
  app/cdash/tests/CMakeLists.txt
  phpstan-baseline.neon
  tests/Unit/app/Models/TestOutputTest.php
Labels: release notes: fixes

#2836 Fixed download of mulitple attached files
  app/cdash/app/Controller/Api/TestDetails.php
Labels: release notes: fixes

#2813 Remove remaining legacy repository logic
  app/cdash/app/Model/Repository.php
  app/cdash/tests/kwtest/kw_web_tester.php
  app/cdash/tests/test_builddetails.php
  database/migrations/2025_04_17_133618_repository_viewer_types.php
Labels: release notes: deprecated / removed

#2828 Throw exceptions for filesystem errors
  app/Http/Controllers/SubmissionController.php
  app/cdash/include/dailyupdates.php
  app/cdash/tests/kwtest/kw_web_tester.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  config/filesystems.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2831 Limit scope of default route handler
  app/Http/Controllers/CDash.php
  routes/web.php
Labels: release notes: maintenance

#2839 Remove `wget` from Debian-based image
  Dockerfile
Labels: release notes: maintenance

#2835 Remove legacy `UserProject` model
  app/Http/Controllers/UserController.php
  app/cdash/app/Model/Project.php
  app/cdash/app/Model/UserProject.php
  app/cdash/public/api/v1/project.php
  app/cdash/tests/test_authtoken.php
  app/cdash/tests/test_issuecreation.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2834 Remove "site maintainer" project access level
  app/Models/Project.php
  app/cdash/app/Model/Project.php
  app/cdash/include/common.php
  database/migrations/2025_04_29_184206_remove_project_site_maintainer_role.php
Labels: release notes: deprecated / removed
