Repository Kitware/CDash, pull requests merged in 2025-02, with the labels that each got.

#2696 Wait for items to be displayed in SitesIdPageTest
  tests/Browser/Pages/SitesIdPageTest.php
Labels: release notes: maintenance

#2699 Create storage directories for worker containers
  docker/docker-entrypoint.sh
Labels: release notes: administration

#2701 Edit site description directly from `/sites/<id>`
  app/GraphQL/Mutations/UpdateSiteDescription.php
  app/Http/Controllers/SiteController.php
  app/Models/SiteInformation.php
  app/cdash/public/editSite.xsl
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/components/SitesIdPage.vue
  resources/js/vue/components/UserHomepage.vue
  routes/web.php
  tests/Browser/Pages/SitesIdPageTest.php
  tests/Feature/GraphQL/Mutations/UpdateSiteDescriptionTest.php
Labels: release notes: features

#2704 Make buildgroup description column nullable
  app/Models/BuildGroup.php
  app/cdash/app/Model/BuildGroup.php
  database/migrations/2025_02_07_140349_nullable_buildgroup_description.php
Labels: release notes: fixes

#2703 Remove `dailyupdatefile` table
  app/Console/Commands/CleanDatabase.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/cdash/app/Model/Project.php
  app/cdash/include/dailyupdates.php
  app/cdash/public/manageProjectRoles.xsl
  app/cdash/tests/test_removebuilds.php
  database/migrations/2025_02_06_220212_drop_dailyupdatefile_table.php
  phpstan-baseline.neon
Labels: release notes: deprecated / removed

#2706 Standardize header menus
  app/Http/Controllers/ManageBannerController.php
  resources/js/vue/app.js
  resources/js/vue/components/page-header/HeaderMenu.vue
  resources/views/admin/banner.blade.php
  resources/views/components/header.blade.php
  tests/CMakeLists.txt
  tests/Spec/page-header/header-menu.spec.js
  tests/cypress/e2e/tests.cy.js
Labels: release notes: user experience

#2707 Stick header to top of screen on scroll
  resources/css/common.css
Labels: release notes: user experience

#2708 Remove unused config options
  config/cdash.php
Labels: release notes: maintenance

#2711 Fix buggy site information deduplication behavior
  app/Http/Submission/Traits/UpdatesSiteInformation.php
  app/Models/SiteInformation.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/case/CDash/TestUseCaseTest.php
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/configure_handler.php
  app/cdash/xml_handlers/coverage_handler.php
  app/cdash/xml_handlers/coverage_junit_handler.php
  app/cdash/xml_handlers/dynamic_analysis_handler.php
  app/cdash/xml_handlers/note_handler.php
  app/cdash/xml_handlers/testing_handler.php
  app/cdash/xml_handlers/testing_j_unit_handler.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
  tests/Browser/Pages/SitesIdPageTest.php
  tests/Feature/GraphQL/Mutations/UpdateSiteDescriptionTest.php
  tests/Feature/Traits/UpdatesSiteInformationTest.php
Labels: release notes: fixes

#2709 Remove obsolete user credentials feature
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/ManageProjectRolesController.php
  app/Http/Controllers/SubscribeProjectController.php
  app/Http/Controllers/UserController.php
  app/cdash/app/Controller/Api/Index.php
  app/cdash/app/Model/Build.php
  app/cdash/app/Model/Subscriber.php
  app/cdash/app/Model/SubscriberInterface.php
  app/cdash/app/Model/User.php
  app/cdash/app/Model/UserProject.php
  app/cdash/include/dailyupdates.php
  app/cdash/public/manageProjectRoles.xsl
  app/cdash/public/subscribeProject.xsl
  app/cdash/tests/test_email.php
  app/cdash/tests/test_manageprojectroles.php
  database/migrations/2025_02_12_204506_drop_user2repository_table.php
  phpstan-baseline.neon
  resources/js/angular/views/partials/build.html
  resources/views/admin/ajax-find-user-project.blade.php
  resources/views/auth/profile.blade.php
Labels: release notes: maintenance

#2714 Bump version to 3.8.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2713 Wait for element to be visible in SitesIdPageTest
  tests/Browser/Pages/SitesIdPageTest.php
Labels: release notes: maintenance

#2712 Add XML path matching method to XML handlers
  app/Utils/Stack.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/configure_handler.php
  app/cdash/xml_handlers/coverage_handler.php
  app/cdash/xml_handlers/coverage_junit_handler.php
  app/cdash/xml_handlers/coverage_log_handler.php
  app/cdash/xml_handlers/dynamic_analysis_handler.php
  app/cdash/xml_handlers/note_handler.php
  app/cdash/xml_handlers/testing_handler.php
  app/cdash/xml_handlers/testing_j_unit_handler.php
  app/cdash/xml_handlers/update_handler.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2716 Delete unused `common.php` functions
  app/cdash/include/common.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2718 Remove unused `http-factory-guzzle` dependency
  composer.json
  composer.lock
Labels: release notes: external dependencies
