Repository Kitware/CDash, pull requests merged in 2025-06, with the labels that each got.

#2904 Upgrade to Laravel 11
  app/Models/AuthToken.php
  app/Models/BlockedBuild.php
  app/Models/Build.php
  app/Models/BuildCommand.php
  app/Models/BuildCommandOutput.php
  app/Models/BuildConfigure.php
  app/Models/BuildGroup.php
  app/Models/BuildGroupPosition.php
  app/Models/BuildUpdate.php
  app/Models/Comment.php
  app/Models/Configure.php
  app/Models/Coverage.php
  app/Models/CoverageFile.php
  app/Models/GlobalInvitation.php
  app/Models/Measurement.php
  app/Models/Note.php
  app/Models/Project.php
  app/Models/ProjectInvitation.php
  app/Models/RichBuildAlert.php
  app/Models/RichBuildAlertDetails.php
  app/Models/Site.php
  app/Models/SiteInformation.php
  app/Models/SubProject.php
  app/Models/Target.php
  app/Models/Test.php
  app/Models/TestImage.php
  app/Models/TestOutput.php
  app/Models/UploadFile.php
  app/Models/User.php
  app/Utils/DatabaseCleanupUtils.php
  app/cdash/app/Model/Project.php
  composer.json
  composer.lock
  config/database.php
  phpstan-baseline.neon
  phpstan.neon
  resources/providers/PingIdentity/composer.json
Labels: release notes: external dependencies

#2920 Use cache-busting Webpack chunk names in development
  webpack.mix.js
Labels: release notes: maintenance

#2921 Overhaul build files page
  app/Http/Controllers/BuildController.php
  app/Models/UploadFile.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_uploadfile.php
  graphql/schema.graphql
  resources/js/vue/app.js
  resources/js/vue/components/BuildFilesPage.vue
  resources/views/build/files.blade.php
  tests/Browser/Pages/BuildFilesPageTest.php
Labels: release notes: user experience

#2889 Add GraphQL relationship filters
  app/GraphQL/Directives/FilterDirective.php
  phpstan-baseline.neon
  tests/Feature/GraphQL/FilterTest.php
Labels: release notes: features

#2927 Update to PHPStan 2.x
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpstan.neon
Labels: release notes: external dependencies

#2925 Clean up legacy test dependencies
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/autoremovebuilds/CMakeLists.txt
  app/cdash/tests/test_issuecreation.php
  tests/cypress/e2e/tests.cy.js
Labels: release notes: maintenance

#2932 Reduce test flakiness
  app/cdash/tests/CMakeLists.txt
Labels: release notes: maintenance

#2934 Fix a couple errors I noticed in our logs
  app/Http/Controllers/TestController.php
  app/cdash/include/dailyupdates.php
Labels: release notes: fixes

#2935 Specify multiple processors for resource-intensive tests
  app/cdash/tests/CMakeLists.txt
  phpstan.neon
  tests/CMakeLists.txt
  tests/cypress/component/CMakeLists.txt
  tests/cypress/e2e/CMakeLists.txt
Labels: release notes: maintenance

#2937 Fix abstract class mock deprecation warnings
  app/cdash/tests/case/CDash/Messaging/Subscription/UserSubscriptionBuilderTest.php
  app/cdash/tests/case/CDash/Messaging/Topic/AuthoredTopicTest.php
  app/cdash/tests/case/CDash/Messaging/Topic/ConfigureTopicTest.php
  app/cdash/tests/case/CDash/Messaging/Topic/EmailSentTopicTest.php
  app/cdash/tests/case/CDash/Messaging/Topic/TopicDecoratorTest.php
  app/cdash/tests/case/CDash/Service/RepositoryServiceTest.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2938 Refactor `LoginAndRegistration` test
  phpstan-baseline.neon
  tests/Feature/LoginAndRegistration.php
  tests/Traits/CreatesUsers.php
Labels: release notes: maintenance

#2940 Move data providers to PHP attributes
  tests/Feature/GraphQL/BuildCommandTypeTest.php
  tests/Feature/GraphQL/Mutations/CreateGlobalInvitationTest.php
  tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/Feature/GraphQL/TargetTypeTest.php
  tests/Feature/GraphQL/TestTypeTest.php
  tests/Feature/LoginAndRegistration.php
  tests/Feature/RouteAccessTest.php
Labels: release notes: maintenance

#2942 Upgrade to PHPUnit 12
  composer.json
  composer.lock
Labels: release notes: external dependencies

#2945 Fix missing log messages for UBI images
  Dockerfile
Labels: release notes: fixes

#2943 Replace `note` `crc32` column with hash index
  app/Models/Note.php
  app/Utils/NoteCreator.php
  app/cdash/tests/test_removebuilds.php
  database/migrations/2025_06_17_140642_drop_note_crc32.php
  phpstan-baseline.neon
  tests/Feature/GraphQL/NoteTypeTest.php
Labels: release notes: maintenance

#2947 Refactor legacy `BuildUpdate` model to use Eloquent
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/UserController.php
  app/Jobs/ProcessSubmission.php
  app/Models/Build.php
  app/Models/BuildUpdate.php
  app/Utils/RepositoryUtils.php
  app/cdash/app/Model/BuildUpdate.php
  app/cdash/tests/case/CDash/Model/BuildUpdateTest.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2949 Fix GraphQL-based filter interface
  resources/js/vue/components/BuildTestsPage.vue
  resources/js/vue/components/shared/FilterGroup.vue
  resources/js/vue/components/shared/FilterRow.vue
Labels: release notes: fixes

#2941 Decompress test output
  app/Models/TestOutput.php
  app/Utils/TestCreator.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/TestDetails.php
  app/cdash/tests/CMakeLists.txt
  database/migrations/2025_06_16_152800_decompress_test_output.php
  phpstan-baseline.neon
  tests/Unit/app/Models/TestOutputTest.php
Labels: release notes: maintenance
