Repository Kitware/CDash, pull requests merged in 2025-05, with the labels that each got.

#2837 Add support for build command outputs
  app/Models/BuildCommand.php
  app/Models/BuildCommandOutput.php
  app/Validators/Schemas/Build.xsd
  app/cdash/tests/CMakeLists.txt
  app/cdash/xml_handlers/build_handler.php
  database/migrations/2025_04_30_110457_build_command_outputs.php
  graphql/schema.graphql
  tests/Feature/GraphQL/BuildCommandOutputTypeTest.php
  tests/Feature/Submission/Instrumentation/BuildInstrumentationTest.php
  tests/Feature/Submission/Instrumentation/data/Build.xml
  tests/Feature/Submission/Instrumentation/data/result.json
Labels: release notes: features

#2838 Send httpd logs to stderr when using UBI as base
  Dockerfile
  docker/cdash-site.conf
Labels: release notes: administration

#2854 Update `.gitignore` list
  .gitignore
Labels: release notes: maintenance

#2855 Clean up simple Cypress test dependencies
  tests/cypress/e2e/CMakeLists.txt
  tests/cypress/e2e/sites.cy.js
Labels: release notes: maintenance

#2857 Delete unused `MigrationTest` abstract class
  tests/MigrationTest.php
Labels: release notes: maintenance

#2866 Remove `all-projects` Cypress test
  tests/cypress/e2e/CMakeLists.txt
  tests/cypress/e2e/all-projects.cy.js
Labels: release notes: maintenance

#2856 Add admin button to delete project members
  app/GraphQL/Mutations/RemoveProjectUser.php
  app/Policies/ProjectPolicy.php
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/components/ProjectMembersPage.vue
  resources/views/project/members.blade.php
  tests/Browser/Pages/ProjectMembersPageTest.php
  tests/Feature/GraphQL/Mutations/RemoveProjectUserTest.php
Labels: release notes: features

#2858 Remove legacy `UploadFile` model
  app/Http/Controllers/BuildController.php
  app/cdash/app/Model/Build.php
  app/cdash/app/Model/UploadFile.php
  app/cdash/tests/test_removebuilds.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2860 Improve GraphQL filter validation
  app/GraphQL/Directives/FilterDirective.php
  phpstan-baseline.neon
  tests/Feature/GraphQL/FilterTest.php
Labels: release notes: user experience

#2861 Automate filter input type creation
  app/GraphQL/Directives/FilterDirective.php
  app/GraphQL/Directives/FilterableDirective.php
  graphql/schema.graphql
  phpstan-baseline.neon
Labels: release notes: maintenance

#2859 Remove database queries from submission handler constructors
  app/cdash/app/Model/BuildErrorFilter.php
  app/cdash/app/Model/Project.php
  app/cdash/xml_handlers/BazelJSON_handler.php
  app/cdash/xml_handlers/GcovTar_handler.php
  app/cdash/xml_handlers/SubProjectDirectories_handler.php
  app/cdash/xml_handlers/abstract_submission_handler.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  app/cdash/xml_handlers/build_handler.php
  app/cdash/xml_handlers/coverage_handler.php
  app/cdash/xml_handlers/coverage_log_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2863 Set project image and title on initial page load
  app/Http/Controllers/AbstractController.php
  app/Http/Controllers/AbstractProjectController.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AuthTokenController.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/BuildPropertiesController.php
  app/Http/Controllers/CTestConfigurationController.php
  app/Http/Controllers/CoverageController.php
  app/Http/Controllers/DynamicAnalysisController.php
  app/Http/Controllers/IndexController.php
  app/Http/Controllers/MonitorController.php
  app/Http/Controllers/ProjectOverviewController.php
  app/Http/Controllers/SiteController.php
  app/Http/Controllers/SubProjectController.php
  app/Http/Controllers/TestController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/ViewProjectsController.php
  app/Http/Controllers/ViewTestController.php
  phpstan-baseline.neon
  resources/js/vue/app.js
  resources/js/vue/components/page-header/HeaderLogo.vue
  resources/views/components/header.blade.php
Labels: release notes: user experience

#2870 Disable manual project membership when LDAP enabled
  app/Console/Kernel.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/ProjectInvitationController.php
  app/Listeners/SuccessfulLdapAuthListener.php
  app/Policies/ProjectPolicy.php
  config/cdash.php
  tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
  tests/Feature/GraphQL/Mutations/RemoveProjectUserTest.php
Labels: release notes: features

#2868 Use GHA arm64 runners for arm64 image build job
  .github/workflows/ci.yml
Labels: release notes: maintenance

#2871 Load minimal set of icons for each page
  resources/js/vue/app.js
  resources/js/vue/components/ProjectMembersPage.vue
  resources/js/vue/components/SitesIdPage.vue
  resources/js/vue/components/UserHomepage.vue
  resources/js/vue/components/UsersPage.vue
  resources/js/vue/components/shared/BuildSummaryCard.vue
  resources/js/vue/components/shared/BuildSummaryCardStepSummary.vue
  resources/js/vue/components/shared/DataTable.vue
  resources/js/vue/components/shared/FilterBuilder.vue
  resources/js/vue/components/shared/FilterGroup.vue
  resources/js/vue/components/shared/FilterRow.vue
  webpack.mix.js
Labels: release notes: performance

#2872 Move contents of `ctestparser.php` to submission handler
  app/Http/Controllers/AdminController.php
  app/Jobs/ProcessSubmission.php
  app/cdash/include/ctestparser.php
  app/cdash/tests/test_donehandler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2873 Adjust waits in flaky `sub-project-group-order` test
  tests/cypress/e2e/sub-project-group-order.cy.js
Labels: release notes: maintenance

#2874 Fix sporadic email unique constraint testing issues
  phpstan-baseline.neon
  tests/Browser/Pages/ProjectMembersPageTest.php
  tests/Feature/GlobalInvitationAcceptanceTest.php
  tests/Feature/GraphQL/Mutations/CreateGlobalInvitationTest.php
  tests/Feature/GraphQL/Mutations/InviteToProjectTest.php
  tests/Feature/GraphQL/Mutations/RevokeGlobalInvitationTest.php
  tests/Feature/GraphQL/Mutations/RevokeProjectInvitationTest.php
  tests/Feature/GraphQL/UserInvitationTypeTest.php
  tests/Feature/ProjectInvitationAcceptanceTest.php
Labels: release notes: maintenance

#2876 Update `laravel-graphiql` to 4.0.1
  .eslintignore
  composer.json
  composer.lock
  install.sh
  resources/views/vendor/graphiql/index.blade.php
Labels: release notes: external dependencies

#2878 Bump `laravel-graphiql` to 3.3.3
  composer.json
  composer.lock
Labels: release notes: external dependencies

#2879 Bump version to 3.10.2
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2877 Set basic Content Security Policy
  public/.htaccess
Labels: release notes: maintenance

#2880 Use common Blade template for Vue-only pages
  app/Http/Controllers/AbstractController.php
  app/Http/Controllers/AuthTokenController.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/DynamicAnalysisController.php
  app/Http/Controllers/EditProjectController.php
  app/Http/Controllers/ManageMeasurementsController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/ProjectMembersController.php
  app/Http/Controllers/SiteController.php
  app/Http/Controllers/SubProjectController.php
  app/Http/Controllers/TestController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/UsersController.php
  phpstan-baseline.neon
  resources/views/admin/manage-authtokens.blade.php
  resources/views/admin/measurements.blade.php
  resources/views/admin/project.blade.php
  resources/views/admin/user.blade.php
  resources/views/build/tests.blade.php
  resources/views/dynamicanalysis/dynamic-analysis.blade.php
  resources/views/project/members.blade.php
  resources/views/project/sites.blade.php
  resources/views/project/subproject-dependencies.blade.php
  resources/views/site/view-site.blade.php
  resources/views/test/details.blade.php
  resources/views/user/users.blade.php
  resources/views/vue.blade.php
Labels: release notes: maintenance

#2882 Fix undefined variable code path in remove builds method
  app/Http/Controllers/AdminController.php
  app/Utils/DatabaseCleanupUtils.php
  app/cdash/include/common.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2883 Remove "email administrator" project setting
  app/Jobs/ProcessSubmission.php
  app/Models/Project.php
  app/cdash/app/Model/Project.php
  app/cdash/tests/test_createpublicdashboard.php
  app/cdash/tests/test_pubproject.php
  database/migrations/2025_05_12_145045_remove_emailadministrator_project_config.php
  phpstan-baseline.neon
  resources/js/vue/components/EditProject.vue
Labels: release notes: deprecated / removed

#2884 Remove misc. dead code
  app/Console/Commands/ValidateXml.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/CoverageController.php
  app/Http/Controllers/ProjectOverviewController.php
  app/Http/Controllers/SubmissionController.php
  app/Http/Controllers/SubscribeProjectController.php
  app/Http/Controllers/TestController.php
  app/Http/Controllers/UserController.php
  app/Jobs/ProcessSubmission.php
  app/Providers/EventServiceProvider.php
  app/Utils/TestDiffUtil.php
  app/Utils/UnparsedSubmissionProcessor.php
  app/cdash/app/Controller/Api/Index.php
  app/cdash/app/Controller/Api/ResultsApi.php
  app/cdash/app/Controller/Api/TestOverview.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/Build.php
  app/cdash/app/Model/Coverage.php
  app/cdash/app/Model/CoverageFile.php
  app/cdash/app/Model/CoverageSummary.php
  app/cdash/app/Model/DynamicAnalysis.php
  app/cdash/app/Model/DynamicAnalysisSummary.php
  app/cdash/app/Model/Label.php
  app/cdash/include/Messaging/Subscription/UserSubscriptionBuilder.php
  app/cdash/include/Messaging/Topic/Topic.php
  app/cdash/include/common.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/public/api/v1/buildgroup.php
  app/cdash/tests/test_aggregatesubprojectcoverage.php
  app/cdash/tests/test_authtoken.php
  app/cdash/tests/test_buildgetdate.php
  app/cdash/tests/test_buildgrouprule.php
  app/cdash/tests/test_buildproperties.php
  app/cdash/tests/test_buildrelationship.php
  app/cdash/tests/test_email.php
  app/cdash/tests/test_extracttar.php
  app/cdash/tests/test_managemeasurements.php
  app/cdash/tests/test_multiplesubprojects.php
  app/cdash/tests/test_notesparsererrormessages.php
  app/cdash/tests/test_projectwebpage.php
  app/cdash/tests/test_putdynamicbuilds.php
  app/cdash/tests/test_redundanttests.php
  app/cdash/tests/test_timeline.php
  app/cdash/tests/test_uniquediffs.php
  app/cdash/xml_handlers/BazelJSON_handler.php
  app/cdash/xml_handlers/OpenCoverTar_handler.php
  app/cdash/xml_handlers/done_handler.php
  app/cdash/xml_handlers/update_handler.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
  resources/views/admin/ajax-find-user-project.blade.php
  resources/views/admin/find-users.blade.php
  routes/web.php
Labels: release notes: maintenance

#2887 Add option to customize OAuth button text
  config/services.php
  docs/authentication.md
  tests/Feature/LoginAndRegistration.php
Labels: release notes: features

#2886 Download GraphiQL assets during Docker build
  Dockerfile
  install.sh
Labels: release notes: maintenance

#2875 Add CTest dependencies automatically
  CMakeLists.txt
  app/cdash/tests/CMakeLists.txt
  tests/CMakeLists.txt
Labels: release notes: maintenance

#2890 Increase the size of the testmeasurement.name field
  database/migrations/2025_05_19_172027_increase_testmeasurement_name_size.php
Labels: release notes: fixes

#2891 Enable HTTP Compression
  public/.htaccess
Labels: release notes: performance

#2892 Fix configuration checks for local vs. remote storage
  app/Http/Controllers/RemoteProcessingController.php
  app/cdash/include/common.php
  app/cdash/tests/test_donehandler.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  app/cdash/xml_handlers/retry_handler.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2894 Fix project and global invitation access control issues
  app/Policies/GlobalInvitationPolicy.php
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  phpstan-baseline.neon
  tests/Feature/GraphQL/GlobalInvitationTypeTest.php
  tests/Feature/GraphQL/ProjectInvitationTypeTest.php
Labels: release notes: fixes

#2885 Drop MySQL support
  .env.example
  .github/workflows/ci.yml
  Dockerfile
  composer.json
  config/database.php
  config/queue.php
  docker/docker-compose.mysql.yml
  docker/docker-compose.postgres.yml
  docs/config.md
  docs/docker.md
  docs/install.md
Labels: release notes: deprecated / removed

#2897 Remove MySQL-specific code paths
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/MonitorController.php
  app/Http/Controllers/SiteController.php
  app/Providers/AppServiceProvider.php
  app/Utils/SubmissionUtils.php
  app/cdash/app/Controller/Api/Index.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/BuildUpdate.php
  app/cdash/app/Model/CoverageFileLog.php
  app/cdash/app/Model/DynamicAnalysis.php
  app/cdash/app/Model/Label.php
  app/cdash/app/Model/Project.php
  app/cdash/include/common.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/public/api/v1/buildgroup.php
  app/cdash/tests/kwtest/kw_db.php
  app/cdash/tests/test_projectindb.php
  config/database.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2893 Make partial text match filters case-insensitive
  app/cdash/include/filterdataFunctions.php
Labels: release notes: features

#2898 Move join/leave project functionality to members page
  app/GraphQL/Mutations/JoinProject.php
  app/GraphQL/Mutations/RemoveProjectUser.php
  app/Http/Controllers/ProjectMembersController.php
  app/Http/Controllers/SubscribeProjectController.php
  app/Policies/ProjectPolicy.php
  app/cdash/public/subscribeProject.xsl
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_email.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/components/ProjectMembersPage.vue
  resources/views/components/header.blade.php
  tests/Browser/Pages/ProjectMembersPageTest.php
  tests/Feature/GraphQL/Mutations/JoinProjectTest.php
  tests/Feature/GraphQL/Mutations/RemoveProjectUserTest.php
Labels: release notes: features

#2901 Bump version to 4.0.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored
