Repository Kitware/CDash, pull requests merged in 2025-09, with the labels that each got.

#3107 Add context to installation ID exception message
  app/cdash/app/Lib/Repository/GitHub.php
Labels: release notes: maintenance

#3110 compose: configure containers to restart
  docker/docker-compose.postgres.yml
  docker/docker-compose.production.yml
Labels: release notes: administration

#3111 Fix CSV download when measurements present
  app/cdash/app/Controller/Api/ViewTest.php
  phpstan-baseline.neon
Labels: release notes: fixes

#3128 Bump version to 4.4.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#3129 Bump version to 4.4.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#3131 Move build pruning to a scheduled job
  app/Console/Kernel.php
  app/Jobs/PruneBuilds.php
  app/Models/BuildGroup.php
  app/Utils/DatabaseCleanupUtils.php
  app/cdash/include/dailyupdates.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/autoremovebuilds/CMakeLists.txt
  app/cdash/tests/test_autoremovebuilds_on_submit.php
  app/cdash/tests/test_notesparsererrormessages.php
  app/cdash/tests/test_summaryemail.php
  phpstan-baseline.neon
  tests/Feature/Jobs/PruneBuildsTest.php
Labels: release notes: maintenance

#3120 Delete unused daily updates code
  app/cdash/include/dailyupdates.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3126 Improve submission-time logging
  app/Http/Controllers/SubmissionController.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3127 Update links to redirect routes throughout site
  app/Http/Controllers/TestController.php
  app/Models/Test.php
  app/Utils/RepositoryUtils.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/TestDetails.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/tests/test_issuecreation.php
  app/cdash/tests/test_testhistory.php
  app/cdash/tests/test_timeoutsandmissingtests.php
  resources/js/angular/views/index.html
  resources/js/angular/views/partials/build.html
  resources/js/vue/components/EditProject.vue
  resources/js/vue/components/ManageMeasurements.vue
  resources/js/vue/components/TestDetails.vue
  resources/js/vue/components/UserHomepage.vue
  resources/views/coverage/ajax-coverage-graph.blade.php
  resources/views/test/view-test.blade.php
  tests/cypress/e2e/view-test.cy.js
Labels: release notes: maintenance

#3133 Remove `api_common.php`
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/TestController.php
  app/Http/Controllers/ViewTestController.php
  app/cdash/app/Controller/Api/TestGraph.php
  app/cdash/app/Controller/Api/TestOverview.php
  app/cdash/app/Controller/Api/Timeline.php
  app/cdash/include/api_common.php
  app/cdash/include/common.php
  app/cdash/public/api/v1/GitHub/webhook.php
  app/cdash/public/api/v1/buildgroup.php
  app/cdash/public/api/v1/computeClassifier.php
  app/cdash/public/api/v1/index.php
  app/cdash/public/api/v1/project.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3135 Sort testSummary rows deterministically in e2e test
  tests/cypress/e2e/test-summary.cy.js
  tests/cypress/e2e/tests.cy.js
Labels: release notes: maintenance

#3137 Delete trivial `sitestatistics` test
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_sitestatistics.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3141 Change default LDAP logging level to `debug`
  config/ldap.php
Labels: release notes: administration

#3142 Handle invalid project LDAP filters
  app/Utils/LdapUtils.php
  tests/Feature/LdapIntegration.php
Labels: release notes: fixes
