Repository Kitware/CDash, pull requests merged in 2025-03, with the labels that each got.

#2681 Build arm64 images in CI
  .github/workflows/ci.yml
Labels: release notes: maintenance

#2717 Introduce try/catch for image creation
  app/Utils/TestCreator.php
  public/img/image_missing.png
Labels: release notes: fixes

#2745 Bump version to 3.9.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2746 Merge 3.9 into master
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2747 Don't show dynamic buildgroups on the wildcard tab
  resources/js/angular/views/manageBuildGroup.html
Labels: release notes: fixes

#2748 Improve submission times by indexing `updatefile(filename)
  database/migrations/2025_03_21_201854_updatefile_filename_index.php
Labels: release notes: performance

#2749 Move upload pruning from submission handler to scheduled job
  app/Console/Kernel.php
  app/Jobs/PruneUploads.php
  app/Models/Build.php
  app/Models/Project.php
  app/Models/UploadFile.php
  app/cdash/app/Model/Project.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/xml_handlers/upload_handler.php
  database/migrations/2025_03_25_130812_uploadfile_fileid_foreign_key_constraint.php
  phpstan-baseline.neon
  tests/Feature/Jobs/PruneUploadsTest.php
Labels: release notes: performance

#2750 Disable scheduled jobs when not in production
  docker/docker-entrypoint.sh
Labels: release notes: administration

#2753 Add ModelName as valid Site attribute
  app/Validators/Schemas/common.xsd
Labels: release notes: fixes

#2754 Introduce move to correct storage for failing submissions
  app/Http/Controllers/SubmissionController.php
Labels: release notes: fixes

#2755 Fix divide-by-zero error when coverage results have no lines
  app/Http/Controllers/BuildController.php
  phpstan-baseline.neon
Labels: release notes: fixes
