Repository Kitware/CDash, pull requests merged in 2025-01, with the labels that each got.

#2646 Remove unnecessary Composer hooks
  composer.json
Labels: release notes: maintenance

#2645 Remove `laravel/legacy-factories` dependency
  app/cdash/tests/kwtest/kw_web_tester.php
  composer.json
  composer.lock
Labels: release notes: maintenance

#2650 Remove `cdash_unlink()` helper
  app/cdash/include/dailyupdates.php
  app/cdash/include/log.php
  app/cdash/xml_handlers/upload_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2652 Update license year to 2025
  LICENSE
Labels: release notes: documentation

#2653 Replace usages of deprecated `setMethods()` method
  app/cdash/include/Test/CDashTestCase.php
  app/cdash/include/Test/CDashUseCaseTestCase.php
  app/cdash/tests/case/CDash/Model/BuildErrorTest.php
  app/cdash/tests/case/CDash/NightlyTimeTest.php
  phpstan-baseline.neon
  tests/Unit/app/Validators/PasswordTest.php
Labels: release notes: maintenance

#2648 Remove `nyholm/psr7` dependency
  composer.json
  composer.lock
Labels: release notes: maintenance

#2656 Fix AuthTokenUtil SQL query
  app/Utils/AuthTokenUtil.php
Labels: release notes: fixes

#2658 Replace usages of `add_log()` method with Log facade
  app/Http/Controllers/AbstractBuildController.php
  app/Http/Controllers/AbstractProjectController.php
  app/Jobs/ProcessSubmission.php
  app/Listeners/EmailSentListener.php
  app/Utils/RepositoryUtils.php
  app/cdash/app/Model/Build.php
  app/cdash/app/Model/BuildConfigure.php
  app/cdash/app/Model/BuildError.php
  app/cdash/app/Model/BuildFailure.php
  app/cdash/app/Model/BuildGroupRule.php
  app/cdash/app/Model/BuildRelationship.php
  app/cdash/app/Model/Coverage.php
  app/cdash/app/Model/CoverageFileLog.php
  app/cdash/app/Model/DynamicAnalysis.php
  app/cdash/app/Model/ModelType.php
  app/cdash/app/Model/PendingSubmissions.php
  app/cdash/app/Model/Repository.php
  app/cdash/app/Model/SubProject.php
  app/cdash/app/Model/SubProjectGroup.php
  app/cdash/app/Model/UploadFile.php
  app/cdash/app/Model/UserProject.php
  app/cdash/include/common.php
  app/cdash/include/ctestparser.php
  app/cdash/include/dailyupdates.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/include/log.php
  app/cdash/public/api/v1/GitHub/webhook.php
  app/cdash/public/api/v1/computeClassifier.php
  app/cdash/tests/test_email.php
  app/cdash/tests/test_subproject.php
  app/cdash/tests/test_subprojectemail.php
  app/cdash/tests/test_summaryemail.php
  app/cdash/tests/test_timeoutsandmissingtests.php
  app/cdash/xml_handlers/BazelJSON_handler.php
  app/cdash/xml_handlers/BuildPropertiesJSON_handler.php
  app/cdash/xml_handlers/GcovTar_handler.php
  app/cdash/xml_handlers/JSCoverTar_handler.php
  app/cdash/xml_handlers/JavaJSONTar_handler.php
  app/cdash/xml_handlers/OpenCoverTar_handler.php
  app/cdash/xml_handlers/SubProjectDirectories_handler.php
  app/cdash/xml_handlers/project_handler.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#2660 Bump PHPUnit to 10.5.40
  composer.json
  composer.lock
  phpstan-baseline.neon
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/Feature/GraphQL/TestTypeTest.php
  tests/Feature/RouteAccessTest.php
Labels: release notes: external dependencies

#2654 Protect internal routes with dedicated middleware
  app/Http/Controllers/RemoteProcessingController.php
  app/Http/Kernel.php
  app/Http/Middleware/Internal.php
  app/Jobs/ProcessSubmission.php
  app/cdash/public/api/v1/deleteSubmissionFile.php
  app/cdash/public/api/v1/getSubmissionFile.php
  app/cdash/public/api/v1/requeueSubmissionFile.php
  app/cdash/tests/CMakeLists.txt
  phpstan-baseline.neon
  routes/api.php
  tests/Feature/RemoteWorkers.php
  tests/Unit/app/Middleware/InternalTest.php
Labels: release notes: maintenance

#2661 Overhaul site information page
  .env.example
  app/Http/Controllers/SiteController.php
  app/cdash/public/viewSite.xsl
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_projectwebpage.php
  config/cdash.php
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/app.js
  resources/js/vue/components/SitesIdPage.vue
  resources/views/site/view-site.blade.php
  routes/web.php
  tests/Browser/Pages/ProjectSitesPageTest.php
  tests/Browser/Pages/SitesIdPageTest.php
  tests/BrowserTestCase.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/cypress/e2e/sites.cy.js
Labels: release notes: user experience

#2666 Bump version to 3.7.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2667 Merge 3.7.0 into master
  app/Utils/AuthTokenUtil.php
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#2664 Reformat test dependencies
  app/cdash/tests/CMakeLists.txt
  tests/Feature/GraphQL/BuildTypeTest.php
  tests/Feature/GraphQL/FilterTest.php
  tests/Feature/GraphQL/ProjectTypeTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
  tests/Feature/IncreaseSiteInformationCPUColumnsSizeMigration.php
  tests/Feature/MeasurementPositionMigration.php
  tests/Feature/Monitor.php
  tests/Feature/PurgeUnusedProjectsCommand.php
  tests/Feature/RemoveMeasurementCheckboxesMigration.php
  tests/Feature/UploadStorageMigration.php
Labels: release notes: maintenance

#2670 Restrict build GraphQL test to only the projects it creates
  tests/Feature/GraphQL/BuildTypeTest.php
Labels: release notes: maintenance

#2663 Account for non-xml submission objects
  app/Http/Controllers/SubmissionController.php
  app/Jobs/ProcessSubmission.php
  app/cdash/include/ctestparser.php
  phpstan-baseline.neon
Labels: release notes: fixes

#2677 Start using autoregister as the default for OAuth
  app/Http/Controllers/OAuthController.php
  config/services.php
  tests/Feature/LoginAndRegistration.php
Labels: release notes: deprecated / removed

#2543 Add reusable build information card
  graphql/schema.graphql
  resources/js/vue/app.js
  resources/js/vue/components/BuildTestsPage.vue
  resources/js/vue/components/shared/BuildSummaryCard.vue
  resources/js/vue/components/shared/BuildSummaryCardStepSummary.vue
Labels: release notes: user experience

#2676 Add support for S3 as a remote filesystem
  .env.dev
  .env.example
  .github/workflows/ci.yml
  .github/workflows/ctest_driver_script.cmake
  .github/workflows/submit.sh
  CMakeLists.txt
  app/Console/Commands/ValidateXml.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/RemoteProcessingController.php
  app/Http/Controllers/SubmissionController.php
  app/Jobs/ProcessSubmission.php
  app/Utils/SubmissionUtils.php
  app/Utils/UnparsedSubmissionProcessor.php
  app/cdash/include/common.php
  app/cdash/include/ctestparser.php
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/test_donehandler.php
  app/cdash/tests/test_extracttar.php
  app/cdash/tests/test_uploadfile.php
  app/cdash/xml_handlers/BazelJSON_handler.php
  app/cdash/xml_handlers/BuildPropertiesJSON_handler.php
  app/cdash/xml_handlers/GcovTar_handler.php
  app/cdash/xml_handlers/JSCoverTar_handler.php
  app/cdash/xml_handlers/JavaJSONTar_handler.php
  app/cdash/xml_handlers/OpenCoverTar_handler.php
  app/cdash/xml_handlers/SubProjectDirectories_handler.php
  app/cdash/xml_handlers/abstract_xml_handler.php
  app/cdash/xml_handlers/retry_handler.php
  composer.json
  composer.lock
  config/filesystems.php
  docker/docker-compose.minio.yml
  docs/config.md
  phpstan-baseline.neon
  tests/Feature/RemoteWorkers.php
Labels: release notes: features

#2679 Set default scope for pre-3.2 auth tokens
  database/migrations/2025_01_28_154916_authtoken_default_scope.php
Labels: release notes: fixes

#2680 Add "claim site" functionality to site overview page
  app/GraphQL/Mutations/AbstractMutation.php
  app/GraphQL/Mutations/ClaimSite.php
  app/GraphQL/Mutations/UnclaimSite.php
  app/cdash/tests/CMakeLists.txt
  graphql/schema.graphql
  phpstan-baseline.neon
  resources/js/vue/app.js
  resources/js/vue/components/SitesIdPage.vue
  resources/views/site/view-site.blade.php
  tests/Browser/Pages/SitesIdPageTest.php
  tests/Feature/GraphQL/SiteTypeTest.php
Labels: release notes: features
