Repository Kitware/CDash, pull requests merged in 2025-08, with the labels that each got.

#3040 Remove /CDash/Model/* test dependencies
  app/cdash/tests/CMakeLists.txt
  app/cdash/tests/case/CDash/Model/PendingSubmissionsTest.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3043 Fix undefined class warnings
  app/Console/Commands/QueueSubmissions.php
  app/cdash/app/Lib/Repository/GitHub.php
  app/cdash/app/Model/Build.php
  app/cdash/app/Model/BuildConfigure.php
  app/cdash/include/Messaging/Topic/MissingTestTopic.php
  app/cdash/include/common.php
  app/cdash/tests/case/CDash/TestUseCaseTest.php
  app/cdash/tests/test_branchcoverage.php
  app/cdash/tests/test_deferredsubmissions.php
  app/cdash/tests/test_parallelsubmissions.php
  app/cdash/tests/test_unparsedsubmissionshonorbuildid.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3047 Catch filesystem exception in error handler
  app/Jobs/ProcessSubmission.php
Labels: release notes: fixes

#3049 Move global banner text to top bar
  app/Http/Controllers/SubProjectController.php
  app/cdash/public/api/v1/index.php
  app/cdash/tests/CMakeLists.txt
  config/cdash.php
  phpstan-baseline.neon
  resources/views/components/header.blade.php
  tests/Feature/GlobalBannerTest.php
Labels: release notes: user experience

#3052 Remove measurements from test output crc32 computation
  app/Utils/TestCreator.php
Labels: release notes: fixes

#3050 Use strict equality for string constant comparisons
  app/Console/Commands/AutoRemoveBuilds.php
  app/Console/Commands/SaveUser.php
  app/Http/Controllers/BuildController.php
  app/Http/Controllers/CoverageController.php
  app/Http/Controllers/SubscribeProjectController.php
  app/Http/Submission/Handlers/AbstractXmlHandler.php
  app/Http/Submission/Handlers/BuildHandler.php
  app/Http/Submission/Handlers/ConfigureHandler.php
  app/Http/Submission/Handlers/CoverageHandler.php
  app/Http/Submission/Handlers/CoverageJUnitHandler.php
  app/Http/Submission/Handlers/CoverageLogHandler.php
  app/Http/Submission/Handlers/DoneHandler.php
  app/Http/Submission/Handlers/DynamicAnalysisHandler.php
  app/Http/Submission/Handlers/GcovTarHandler.php
  app/Http/Submission/Handlers/JavaJSONTarHandler.php
  app/Http/Submission/Handlers/NoteHandler.php
  app/Http/Submission/Handlers/OpenCoverTarHandler.php
  app/Http/Submission/Handlers/ProjectHandler.php
  app/Http/Submission/Handlers/TestingHandler.php
  app/Http/Submission/Handlers/TestingJUnitHandler.php
  app/Http/Submission/Handlers/UpdateHandler.php
  app/Jobs/ProcessSubmission.php
  app/Utils/RepositoryUtils.php
  app/cdash/app/Controller/Api/QueryTests.php
  app/cdash/app/Controller/Api/TestDetails.php
  app/cdash/app/Controller/Api/TestGraph.php
  app/cdash/app/Controller/Api/Timeline.php
  app/cdash/app/Controller/Api/ViewTest.php
  app/cdash/app/Model/DynamicAnalysis.php
  app/cdash/app/Model/Project.php
  app/cdash/include/common.php
  app/cdash/include/filterdataFunctions.php
  app/cdash/public/api/v1/GitHub/webhook.php
  app/cdash/public/api/v1/computeClassifier.php
  app/cdash/public/api/v1/manageBuildGroup.php
  app/cdash/tests/kwtest/simpletest/browser.php
  app/cdash/tests/test_autoremovebuilds_on_submit.php
  app/cdash/tests/test_builddetails.php
  app/cdash/tests/test_buildgrouprule.php
  app/cdash/tests/test_buildmodel.php
  app/cdash/tests/test_committerinfo.php
  app/cdash/tests/test_compressedtest.php
  app/cdash/tests/test_managemeasurements.php
  app/cdash/tests/test_multiplesubprojects.php
  app/cdash/tests/test_namedmeasurements.php
  app/cdash/tests/test_redundanttests.php
  app/cdash/tests/test_sequenceindependence.php
  app/cdash/tests/test_subprojecttestfilters.php
  app/cdash/tests/test_testhistory.php
  app/cdash/tests/test_timeline.php
  app/cdash/tests/test_truncateoutput.php
  app/cdash/tests/test_updateappend.php
  app/cdash/tests/trilinos_submission_test.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3061 Clean up DatabaseSeeder
  app/Models/User.php
  composer.json
  database/factories/PasswordFactory.php
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
  phpstan-baseline.neon
Labels: release notes: maintenance

#3064 CSP: Allow inline images
  public/.htaccess
Labels: release notes: fixes

#3068 Bump version to 4.3.0
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#3071 Merge 4.3.0 into master
  config/cdash.php
  package-lock.json
  package.json
Labels: release notes: ignored

#3074 Make saml2 proxyVars configurable
  .env.example
  config/saml2.php
  docs/authentication.md
Labels: release notes: features

#3077 Switch to bitnamilegacy for Docker
  docker/docker-compose.dev.yml
  docker/docker-compose.minio.yml
Labels: release notes: maintenance

#3082 Update join project homepage link
  app/Http/Controllers/SubscribeProjectController.php
  phpstan-baseline.neon
  resources/js/vue/components/UserHomepage.vue
Labels: release notes: user experience
